version: 2
updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: monthly
      timezone: Asia/Hong_Kong
      time: "11:00"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      timezone: Asia/Hong_Kong
      time: "11:10"
