name: collection_change_notifier
description: Implement change notifier for collection object e.g. List, Set and Map
version: 2.0.2
repository: https://github.com/rk0cc/collection_change_notifier
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <5.0.0"
  provider: ^6.1.1

